# Header
menu:
  首页: /
  归档: /archives
  分类: /categories
  标签: /tags
  关于: /about

# Content
excerpt_link: 阅读全文
fancybox: true

# Sidebar
sidebar: right
widgets:
- recent_posts
- category
- tag
- tagcloud
- archive
thumbnail: true

# Contacts
contacts:
  github: http://github.com/wenhao
  twitter: '#'
  facebook: '#'
  dribbble: '#'
  rss: /atom.xml

# webchat
wechat: /css/images/webchat.JPG

# Links
links:
  Hexo: http://hexo.io

# Miscellaneous
google_analytics:
favicon: /favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:

baidu_tongji: true